package auth

import (
	"context"
	"fmt"
	"strings"

	"github.com/coreos/go-oidc/v3/oidc"
	"golang.org/x/oauth2"
)

// OIDCProvider wraps an OpenID Connect provider configuration.
type OIDCProvider struct {
	ID           string
	DisplayName  string
	IssuerURL    string
	ClientID     string
	ClientSecret string
	Scopes       []string
	GroupsClaim  string

	provider *oidc.Provider
	oauth2   *oauth2.Config
}

// OIDCClaims represents the claims extracted from an OIDC ID token.
type OIDCClaims struct {
	Issuer        string   `json:"iss"`
	Subject       string   `json:"sub"`
	Email         string   `json:"email"`
	EmailVerified bool     `json:"email_verified"`
	Name          string   `json:"name"`
	PreferredName string   `json:"preferred_username"`
	Groups        []string `json:"-"`
	// AuthTime is the IdP's `auth_time` claim: when the end-user last
	// actively authenticated, in Unix seconds. Used by OIDC step-up
	// (#279 part 3) to confirm a re-auth actually just happened; some IdPs
	// omit it unless the request carries max_age, which the step-up flow
	// always sets.
	AuthTime int64 `json:"auth_time"`
	// AMR/ACR are captured for future use (enforcing IdP MFA claims is out
	// of scope for #279 part 3) but not otherwise validated yet.
	AMR []string `json:"amr"`
	ACR string   `json:"acr"`
}

// Initialize discovers the OIDC provider and configures the OAuth2 client.
func (p *OIDCProvider) Initialize(ctx context.Context) error {
	provider, err := oidc.NewProvider(ctx, p.IssuerURL)
	if err != nil {
		return fmt.Errorf("discover oidc provider %q: %w", p.IssuerURL, err)
	}
	p.provider = provider

	scopes := p.Scopes
	if len(scopes) == 0 {
		scopes = []string{oidc.ScopeOpenID, "profile", "email"}
	}

	p.oauth2 = &oauth2.Config{
		ClientID:     p.ClientID,
		ClientSecret: p.ClientSecret,
		RedirectURL:  "", // set by the caller based on the incoming request
		Endpoint:     provider.Endpoint(),
		Scopes:       scopes,
	}

	return nil
}

// AuthURL returns the authorization URL for the OIDC provider.
// state is an anti-CSRF token generated by the caller.
// nonce is a per-flow random value that must round-trip in the ID token.
// redirectURL is the callback URL for this authentication flow.
func (p *OIDCProvider) AuthURL(state, nonce, redirectURL string) string {
	return p.configFor(redirectURL).AuthCodeURL(state, oidc.Nonce(nonce))
}

// AuthURLWithOptions is AuthURL with extra authorization-request parameters,
// e.g. `prompt=login` and `max_age=0` to force the IdP to re-prompt for
// credentials during OIDC step-up (#279 part 3) instead of silently
// reusing the browser's existing IdP session.
func (p *OIDCProvider) AuthURLWithOptions(state, nonce, redirectURL string, opts ...oauth2.AuthCodeOption) string {
	allOpts := append([]oauth2.AuthCodeOption{oidc.Nonce(nonce)}, opts...)
	return p.configFor(redirectURL).AuthCodeURL(state, allOpts...)
}

// configFor returns a per-flow copy of the OAuth2 config carrying redirectURL,
// so concurrent requests never share or mutate the provider's config.
func (p *OIDCProvider) configFor(redirectURL string) *oauth2.Config {
	cfg := *p.oauth2
	cfg.RedirectURL = redirectURL
	return &cfg
}

// Exchange exchanges an authorization code for an ID token. expectedNonce must
// match the nonce embedded in the ID token, binding it to the flow that
// requested this code and preventing authorization-code injection.
func (p *OIDCProvider) Exchange(ctx context.Context, code, expectedNonce, redirectURL string) (*OIDCClaims, error) {
	oauth2Token, err := p.configFor(redirectURL).Exchange(ctx, code)
	if err != nil {
		return nil, fmt.Errorf("exchange code: %w", err)
	}

	rawIDToken, ok := oauth2Token.Extra("id_token").(string)
	if !ok {
		return nil, fmt.Errorf("no id_token in oauth2 response")
	}

	verifier := p.provider.Verifier(&oidc.Config{ClientID: p.ClientID})
	idToken, err := verifier.Verify(ctx, rawIDToken)
	if err != nil {
		return nil, fmt.Errorf("verify id_token: %w", err)
	}
	if idToken.Nonce == "" || idToken.Nonce != expectedNonce {
		return nil, fmt.Errorf("id_token nonce mismatch")
	}

	var claims OIDCClaims
	if err := idToken.Claims(&claims); err != nil {
		return nil, fmt.Errorf("parse claims: %w", err)
	}
	if p.GroupsClaim != "" {
		var raw map[string]any
		if err := idToken.Claims(&raw); err != nil {
			return nil, fmt.Errorf("parse dynamic claims: %w", err)
		}
		claims.Groups = extractGroups(raw[p.GroupsClaim])
	}

	claims.Issuer = idToken.Issuer
	return &claims, nil
}

func extractGroups(value any) []string {
	var groups []string
	switch values := value.(type) {
	case []any:
		for _, value := range values {
			if group, ok := value.(string); ok && strings.TrimSpace(group) != "" {
				groups = append(groups, group)
			}
		}
	case []string:
		for _, group := range values {
			if strings.TrimSpace(group) != "" {
				groups = append(groups, group)
			}
		}
	case string:
		if strings.TrimSpace(values) != "" {
			groups = []string{values}
		}
	}
	return groups
}

// IsInitialized returns true if the provider has been successfully initialized.
func (p *OIDCProvider) IsInitialized() bool {
	return p.provider != nil && p.oauth2 != nil
}
