package auth

import (
	"context"
	"fmt"

	"github.com/coreos/go-oidc/v3/oidc"
	"golang.org/x/oauth2"
)

// OIDCProvider wraps an OpenID Connect provider configuration.
type OIDCProvider struct {
	ID           string
	DisplayName  string
	IssuerURL    string
	ClientID     string
	ClientSecret string
	Scopes       []string

	provider *oidc.Provider
	oauth2   *oauth2.Config
}

// OIDCClaims represents the claims extracted from an OIDC ID token.
type OIDCClaims struct {
	Subject       string `json:"sub"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	Name          string `json:"name"`
	PreferredName string `json:"preferred_username"`
}

// Initialize discovers the OIDC provider and configures the OAuth2 client.
func (p *OIDCProvider) Initialize(ctx context.Context) error {
	provider, err := oidc.NewProvider(ctx, p.IssuerURL)
	if err != nil {
		return fmt.Errorf("discover oidc provider %q: %w", p.IssuerURL, err)
	}
	p.provider = provider

	scopes := p.Scopes
	if len(scopes) == 0 {
		scopes = []string{oidc.ScopeOpenID, "profile", "email"}
	}

	p.oauth2 = &oauth2.Config{
		ClientID:     p.ClientID,
		ClientSecret: p.ClientSecret,
		RedirectURL:  "", // set by the caller based on the incoming request
		Endpoint:     provider.Endpoint(),
		Scopes:       scopes,
	}

	return nil
}

// AuthURL returns the authorization URL for the OIDC provider.
// state is an anti-CSRF token generated by the caller.
// redirectURL is the callback URL for this authentication flow.
func (p *OIDCProvider) AuthURL(state, redirectURL string) string {
	p.oauth2.RedirectURL = redirectURL
	return p.oauth2.AuthCodeURL(state)
}

// Exchange exchanges an authorization code for an ID token.
func (p *OIDCProvider) Exchange(ctx context.Context, code string) (*OIDCClaims, error) {
	oauth2Token, err := p.oauth2.Exchange(ctx, code)
	if err != nil {
		return nil, fmt.Errorf("exchange code: %w", err)
	}

	rawIDToken, ok := oauth2Token.Extra("id_token").(string)
	if !ok {
		return nil, fmt.Errorf("no id_token in oauth2 response")
	}

	verifier := p.provider.Verifier(&oidc.Config{ClientID: p.ClientID})
	idToken, err := verifier.Verify(ctx, rawIDToken)
	if err != nil {
		return nil, fmt.Errorf("verify id_token: %w", err)
	}

	var claims OIDCClaims
	if err := idToken.Claims(&claims); err != nil {
		return nil, fmt.Errorf("parse claims: %w", err)
	}

	return &claims, nil
}

// IsInitialized returns true if the provider has been successfully initialized.
func (p *OIDCProvider) IsInitialized() bool {
	return p.provider != nil && p.oauth2 != nil
}
