package sync

import (
	"bytes"
	"crypto/sha256"
	"encoding/csv"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"html/template"
	"strings"
	"time"
)

type SnapshotDiffSource struct {
	ID        string `json:"id"`
	FetchedAt string `json:"fetchedAt"`
	SHA256    string `json:"sha256"`
}
type SnapshotDiffProvenance struct {
	ConnectorID   string             `json:"connectorId"`
	ConnectorName string             `json:"connectorName"`
	From          SnapshotDiffSource `json:"from"`
	To            SnapshotDiffSource `json:"to"`
	GeneratedAt   time.Time          `json:"generatedAt"`
	GeneratedBy   string             `json:"generatedBy"`
}

func SnapshotSourceFromRecord(id, fetchedAt, data string) SnapshotDiffSource {
	hash := sha256.Sum256([]byte(data))
	return SnapshotDiffSource{id, fetchedAt, hex.EncodeToString(hash[:])}
}

func reportValue(v any) string {
	if v == nil {
		return ""
	}
	if s, ok := v.(string); ok {
		return s
	}
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprint(v)
	}
	return string(b)
}

func snapshotReportRows(d SnapshotDiff) [][]string {
	rows := make([][]string, 0, len(d.Sections)+len(d.Entities)+len(d.Dependencies))
	for _, s := range d.Sections {
		for _, p := range s.Patches {
			rows = append(rows, []string{"section", p.Section, "content", s.Type, p.Old, p.New})
		}
	}
	for _, e := range d.Entities {
		rows = append(rows, []string{"entity:" + e.Kind, e.Key, e.Field, e.Change, reportValue(e.Old), reportValue(e.New)})
	}
	for _, dep := range d.Dependencies {
		rows = append(rows, []string{"dependency:" + dep.Kind, dep.Name + ":" + dep.Ref, "dependency", dep.Change, "", ""})
	}
	return rows
}

func RenderSnapshotDiff(d SnapshotDiff, format string) ([]byte, string, error) {
	switch format {
	case "json":
		b, err := json.MarshalIndent(d, "", "  ")
		return append(b, '\n'), "application/json", err
	case "csv":
		var b bytes.Buffer
		p := d.Provenance
		for _, kv := range [][2]string{{"connectorId", p.ConnectorID}, {"connectorName", p.ConnectorName}, {"fromId", p.From.ID}, {"fromFetchedAt", p.From.FetchedAt}, {"fromSha256", p.From.SHA256}, {"toId", p.To.ID}, {"toFetchedAt", p.To.FetchedAt}, {"toSha256", p.To.SHA256}, {"generatedAt", p.GeneratedAt.UTC().Format(time.RFC3339)}, {"generatedBy", p.GeneratedBy}} {
			fmt.Fprintf(&b, "# %s: %s\n", kv[0], strings.ReplaceAll(strings.ReplaceAll(kv[1], "\r", " "), "\n", " "))
		}
		w := csv.NewWriter(&b)
		if err := w.Write([]string{"kind", "key", "field", "change", "old", "new"}); err != nil {
			return nil, "", err
		}
		if err := w.WriteAll(snapshotReportRows(d)); err != nil {
			return nil, "", err
		}
		return b.Bytes(), "text/csv", nil
	case "md":
		return []byte(renderSnapshotMarkdown(d)), "text/markdown", nil
	case "html":
		var b bytes.Buffer
		err := snapshotHTMLTemplate.Execute(&b, struct {
			Diff SnapshotDiff
			Rows [][]string
		}{d, snapshotReportRows(d)})
		return b.Bytes(), "text/html", err
	default:
		return nil, "", fmt.Errorf("unsupported snapshot diff format %q", format)
	}
}

func renderSnapshotMarkdown(d SnapshotDiff) string {
	var b strings.Builder
	p := d.Provenance
	s := d.Summary
	fmt.Fprintf(&b, "# Snapshot diff: %s\n\n", p.ConnectorName)
	fmt.Fprintf(&b, "- Connector ID: %s\n- From: %s (%s)\n- From SHA-256: `%s`\n- To: %s (%s)\n- To SHA-256: `%s`\n- Generated at: %s\n- Generated by: %s\n\n", p.ConnectorID, p.From.ID, p.From.FetchedAt, p.From.SHA256, p.To.ID, p.To.FetchedAt, p.To.SHA256, p.GeneratedAt.UTC().Format(time.RFC3339), p.GeneratedBy)
	fmt.Fprintf(&b, "## Summary\n\nSections: %d added, %d removed, %d modified. Entities: %d added, %d removed, %d modified. Dependencies: %d added, %d removed.\n\n", s.SectionsAdded, s.SectionsRemoved, s.SectionsModified, s.EntitiesAdded, s.EntitiesRemoved, s.EntitiesModified, s.DependenciesAdded, s.DependenciesRemoved)
	fmt.Fprint(&b, "## Sections\n\n")
	for _, section := range d.Sections {
		fmt.Fprintf(&b, "### %s (%s)\n\n", section.Summary, section.Type)
		for _, patch := range section.Patches {
			fmt.Fprintf(&b, "```diff\n%s```\n\n", UnifiedHunks(patch.Old, patch.New))
		}
	}
	fmt.Fprint(&b, "## Entities\n\n")
	for _, e := range d.Entities {
		fmt.Fprintf(&b, "- %s `%s:%s` %s %s: `%s` → `%s`\n", e.Change, e.Kind, e.Key, e.Name, e.Field, reportValue(e.Old), reportValue(e.New))
	}
	fmt.Fprint(&b, "\n## Dependencies\n\n")
	for _, dep := range d.Dependencies {
		fmt.Fprintf(&b, "- %s `%s:%s:%s`\n", dep.Change, dep.Kind, dep.Name, dep.Ref)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

var snapshotHTMLTemplate = template.Must(template.New("snapshotDiff").Funcs(template.FuncMap{"hunks": UnifiedHunks, "timestamp": func(t time.Time) string { return t.UTC().Format(time.RFC3339) }}).Parse(`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Snapshot diff</title><style>body{font:16px system-ui;max-width:80rem;margin:2rem auto;padding:0 1rem}pre{overflow:auto;background:#f3f4f6;padding:1rem}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ddd;padding:.4rem;text-align:left;vertical-align:top}</style></head><body>
<h1>Snapshot diff: {{.Diff.Provenance.ConnectorName}}</h1>
<dl><dt>Connector ID</dt><dd>{{.Diff.Provenance.ConnectorID}}</dd><dt>From</dt><dd>{{.Diff.Provenance.From.ID}} ({{.Diff.Provenance.From.FetchedAt}}), SHA-256 {{.Diff.Provenance.From.SHA256}}</dd><dt>To</dt><dd>{{.Diff.Provenance.To.ID}} ({{.Diff.Provenance.To.FetchedAt}}), SHA-256 {{.Diff.Provenance.To.SHA256}}</dd><dt>Generated at</dt><dd>{{timestamp .Diff.Provenance.GeneratedAt}}</dd><dt>Generated by</dt><dd>{{.Diff.Provenance.GeneratedBy}}</dd></dl>
<h2>Summary</h2><p>Sections: {{.Diff.Summary.SectionsAdded}} added, {{.Diff.Summary.SectionsRemoved}} removed, {{.Diff.Summary.SectionsModified}} modified. Entities: {{.Diff.Summary.EntitiesAdded}} added, {{.Diff.Summary.EntitiesRemoved}} removed, {{.Diff.Summary.EntitiesModified}} modified. Dependencies: {{.Diff.Summary.DependenciesAdded}} added, {{.Diff.Summary.DependenciesRemoved}} removed.</p>
<h2>Sections</h2>{{range .Diff.Sections}}<h3>{{.Summary}} ({{.Type}})</h3>{{range .Patches}}<pre>{{hunks .Old .New}}</pre>{{end}}{{end}}
<h2>Changes</h2><table><thead><tr><th>Kind</th><th>Key</th><th>Field</th><th>Change</th><th>Old</th><th>New</th></tr></thead><tbody>{{range .Rows}}<tr>{{range .}}<td>{{.}}</td>{{end}}</tr>{{end}}</tbody></table></body></html>`))
