package sync

import (
	"encoding/csv"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/WiseLabz/wiselabz/internal/connector"
)

func TestSnapshotDiffEntityFieldsAndCounts(t *testing.T) {
	before := &connector.ServiceSnapshot{Entities: []connector.SnapshotEntity{{Kind: "vm", Name: "Old", ExternalID: "7", IP: "1", Attributes: map[string]any{"enabled": false, "gone": "x"}}, {Kind: "vm", Name: "Removed"}}, Dependencies: []connector.ServiceDependency{{Kind: "host", Name: "a", Ref: "1"}}}
	after := &connector.ServiceSnapshot{Entities: []connector.SnapshotEntity{{Kind: "vm", Name: "New", ExternalID: "7", IP: "2", Attributes: map[string]any{"enabled": true, "new": "y"}}, {Kind: "vm", Name: "Added"}}, Dependencies: []connector.ServiceDependency{{Kind: "host", Name: "b", Ref: "2"}}}
	d := BuildSnapshotDiff(before, after)
	if d.Summary.EntitiesAdded != 1 || d.Summary.EntitiesRemoved != 1 || d.Summary.EntitiesModified != 1 || d.Summary.DependenciesAdded != 1 || d.Summary.DependenciesRemoved != 1 {
		t.Fatalf("summary: %+v", d.Summary)
	}
	want := []string{"externalId:7:attributes.enabled:modified", "externalId:7:attributes.gone:removed", "externalId:7:attributes.new:added", "externalId:7:ip:modified", "externalId:7:name:modified", "name:Added:entity:added", "name:Removed:entity:removed"}
	got := make([]string, 0, len(d.Entities))
	for _, e := range d.Entities {
		got = append(got, e.Key+":"+e.Field+":"+e.Change)
	}
	if strings.Join(got, "|") != strings.Join(want, "|") {
		t.Fatalf("changes: %v, want %v", got, want)
	}
}

func TestSnapshotDiffExports(t *testing.T) {
	before := &connector.ServiceSnapshot{Sections: []connector.SnapshotSection{{Title: "Config", Content: "old\n"}}}
	after := &connector.ServiceSnapshot{Sections: []connector.SnapshotSection{{Title: "Config", Content: "new\n"}}}
	d := BuildSnapshotDiff(before, after)
	d.Provenance = SnapshotDiffProvenance{ConnectorID: "c1", ConnectorName: "<Connector>", From: SnapshotSourceFromRecord("s1", "2026-01-01T00:00:00Z", "old"), To: SnapshotSourceFromRecord("s2", "2026-01-02T00:00:00Z", "new"), GeneratedAt: time.Date(2026, 1, 3, 0, 0, 0, 0, time.UTC), GeneratedBy: "tester"}
	for _, format := range []string{"json", "csv", "md", "html"} {
		b, mime, err := RenderSnapshotDiff(d, format)
		if err != nil || mime == "" || len(b) == 0 {
			t.Fatalf("%s: %s %v", format, mime, err)
		}
		if format == "csv" || format == "md" {
			path := filepath.Join("testdata", "snapshot_diff."+format+".golden")
			if os.Getenv("UPDATE_GOLDEN") == "1" {
				if err := os.WriteFile(path, b, 0644); err != nil {
					t.Fatal(err)
				}
			}
			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			if string(b) != string(want) {
				t.Fatalf("%s differs from golden file", format)
			}
		}
		switch format {
		case "json":
			var decoded SnapshotDiff
			if err := json.Unmarshal(b, &decoded); err != nil || decoded.Provenance.From.SHA256 != d.Provenance.From.SHA256 {
				t.Fatalf("json: %v", err)
			}
		case "csv":
			if !strings.Contains(string(b), "kind,key,field,change,old,new") || !strings.Contains(string(b), "# fromSha256: "+d.Provenance.From.SHA256) {
				t.Fatal(string(b))
			}
		case "md":
			if !strings.Contains(string(b), "```diff") || !strings.Contains(string(b), "Generated by: tester") {
				t.Fatal(string(b))
			}
		case "html":
			if strings.Contains(string(b), "<Connector>") || !strings.Contains(string(b), "&lt;Connector&gt;") {
				t.Fatal("HTML was not escaped")
			}
		}
	}
	if !strings.Contains(UnifiedHunks("old\n", "new\n"), "@@") {
		t.Fatal("missing hunk header")
	}
}

func TestCompareDependenciesDeterministic(t *testing.T) {
	before := []connector.ServiceDependency{{Kind: "storage", Name: "z"}, {Kind: "host", Name: "a"}}
	after := []connector.ServiceDependency{{Kind: "network", Name: "b"}}
	want := "host:a:removed|network:b:added|storage:z:removed"
	for i := 0; i < 20; i++ {
		changes := CompareDependencies(before, after)
		parts := make([]string, 0, len(changes))
		for _, c := range changes {
			parts = append(parts, c.Kind+":"+c.Name+":"+c.Change)
		}
		if got := strings.Join(parts, "|"); got != want {
			t.Fatalf("iteration %d: %s", i, got)
		}
	}
}

func TestCompareEntitiesKeepsExternalIDAndFallbackNameDistinct(t *testing.T) {
	before := &connector.ServiceSnapshot{Entities: []connector.SnapshotEntity{{Kind: "vm", Name: "External", ExternalID: "x", IP: "1"}, {Kind: "vm", Name: "x", IP: "2"}}}
	after := &connector.ServiceSnapshot{Entities: []connector.SnapshotEntity{{Kind: "vm", Name: "External", ExternalID: "x", IP: "3"}, {Kind: "vm", Name: "x", IP: "4"}}}
	d := BuildSnapshotDiff(before, after)
	if d.Summary.EntitiesModified != 2 || len(d.Entities) != 2 {
		t.Fatalf("lost entity: %+v", d)
	}
	if d.Entities[0].Key == d.Entities[1].Key {
		t.Fatalf("colliding keys: %+v", d.Entities)
	}
	if d.Entities[0].Key != "externalId:x" || d.Entities[1].Key != "name:x" {
		t.Fatalf("unexpected keys: %+v", d.Entities)
	}
}

func TestSnapshotDiffCSVNeutralizesFormulaCellsOnly(t *testing.T) {
	d := SnapshotDiff{Sections: []DiffResult{{Type: "modified", Patches: []DiffPatch{{Section: "=SUM(1,2)", Old: " \t+1", New: "safe"}}}}, Entities: []EntityChange{{Kind: "vm", Key: "@key", Field: "name", Change: "modified", Old: "-1", New: "  =HYPERLINK(1)"}}, Dependencies: []DependencyChange{}}
	csvBytes, _, err := RenderSnapshotDiff(d, "csv")
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.SplitN(string(csvBytes), "kind,key,field,change,old,new\n", 2)
	if len(lines) != 2 {
		t.Fatal("missing CSV header")
	}
	rows, err := csv.NewReader(strings.NewReader(lines[1])).ReadAll()
	if err != nil {
		t.Fatal(err)
	}
	if rows[0][1] != "'=SUM(1,2)" || rows[0][4] != "' \t+1" || rows[0][5] != "safe" || rows[1][1] != "'@key" || rows[1][4] != "'-1" || rows[1][5] != "'  =HYPERLINK(1)" {
		t.Fatalf("unsafe CSV rows: %#v", rows)
	}
	jsonBytes, _, err := RenderSnapshotDiff(d, "json")
	if err != nil || strings.Contains(string(jsonBytes), "'@key") {
		t.Fatalf("JSON changed: %s %v", jsonBytes, err)
	}
	mdBytes, _, err := RenderSnapshotDiff(d, "md")
	if err != nil || strings.Contains(string(mdBytes), "'@key") {
		t.Fatalf("Markdown changed: %s %v", mdBytes, err)
	}
	htmlBytes, _, err := RenderSnapshotDiff(d, "html")
	if err != nil || strings.Contains(string(htmlBytes), "'@key") {
		t.Fatalf("HTML changed: %s %v", htmlBytes, err)
	}
}
