/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * How diffs route (§2)
 */
export type AiConfigMode = (typeof AiConfigMode)[keyof typeof AiConfigMode];

export const AiConfigMode = {
  auto_update: 'auto_update',
  suggest_only: 'suggest_only',
} as const;
