/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ApiKeyScope } from './apiKeyScope';

export interface ApiKeyCreate {
  /** @minLength 1 */
  name: string;
  /** Optional expiration; omitted or empty means never. */
  expiresAt?: string;
  scope?: ApiKeyScope;
  /**
   * Optional allow-list of connectors the key can reach. Each must be a connector the caller holds a grant on. A connector-restricted key never acts as instance admin. Omitted or empty means no restriction.
   * @maxItems 100
   */
  connectorIds?: string[];
}
