/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role';

/**
 * One audit trail entry (docs/AUDIT.md). Written only after the audited action succeeds.
 */
export interface AuditRecord {
  id: string;
  actorUserId: string;
  actorRole: Role;
  /** e.g. connector.create, doc.restore */
  action: string;
  /** e.g. connector, doc; empty when the action has no single target */
  targetType: string;
  targetId: string;
  /** Small JSON object, action-specific; never carries secret values (e.g. changed field names, not their values) */
  detail: string;
  createdAt: string;
}
