/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Instance-wide 2FA policy for local accounts (#279). A covered user who hasn't enrolled a factor gets an enrollment-only session at their next login. Changing this doesn't touch existing sessions.
 */
export type AuthConfigRequire2fa = (typeof AuthConfigRequire2fa)[keyof typeof AuthConfigRequire2fa];

export const AuthConfigRequire2fa = {
  none: 'none',
  admins: 'admins',
  all: 'all',
} as const;
