/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Informational only; never applied on import — the encrypted API key can't be restored from a backup
 */
export type BackupBundleAiConfig = {
  enabled?: boolean;
  provider?: string;
  model?: string;
  baseUrl?: string;
  mode?: string;
};
