/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * v1 JSON or v2 ZIP bundle metadata
 */
export type BackupBundleVersion = (typeof BackupBundleVersion)[keyof typeof BackupBundleVersion];

export const BackupBundleVersion = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
