/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { BackupBundleAiConfig } from './backupBundleAiConfig';
import type { BackupBundleTemplateSectionsItem } from './backupBundleTemplateSectionsItem';
import type { BackupBundleTemplatesItem } from './backupBundleTemplatesItem';
import type { BackupBundleVersion } from './backupBundleVersion';
import type { Connector } from './connector';
import type { Doc } from './doc';
import type { DocAttachment } from './docAttachment';
import type { DocVersion } from './docVersion';
import type { EntityIdentityOverrideRecord } from './entityIdentityOverrideRecord';
import type { JournalEntry } from './journalEntry';

/**
 * Portable backup format (docs/BACKUP.md). Connector secret fields (per each connector type's schema) are redacted from `configData`; `aiConfig` never includes the provider API key; notification channel config is not included at all.
 */
export interface BackupBundle {
  journalEntries?: JournalEntry[];
  attachments?: DocAttachment[];
  /** v1 JSON or v2 ZIP bundle metadata */
  version: BackupBundleVersion;
  exportedAt: string;
  connectors: Connector[];
  docs: Doc[];
  docVersions: DocVersion[];
  templates: BackupBundleTemplatesItem[];
  templateSections: BackupBundleTemplateSectionsItem[];
  /** Manual entity identity overrides; members are rebuilt from snapshots after restore, so a restored override stays dormant until its members are observed */
  entityIdentityOverrides?: EntityIdentityOverrideRecord[];
  /** Informational only; never applied on import — the encrypted API key can't be restored from a backup */
  aiConfig?: BackupBundleAiConfig;
}
