/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

export interface BackupSchedule {
  /** 5-field or 6-field (with leading seconds) cron expression */
  cronExpr: string;
  /** Keep at most this many recent backups; 0 or negative disables count-based pruning */
  maxBackups: number;
  /** Delete backups older than this many hours; 0 or negative disables age-based pruning */
  maxAgeHours: number;
  /** Whether the backup job is registered with the scheduler */
  enabled: boolean;
  updatedAt?: string;
}
