/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Flat template record (id, name, description, appliesTo, timestamps) — not the nested Template schema used elsewhere
 */
export type BackupBundleTemplatesItem = {
  id?: string;
  name?: string;
  description?: string;
  appliesTo?: string;
  createdAt?: string;
  updatedAt?: string;
};
