/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { BackupBundleAiConfig } from './backupBundleAiConfig';
import type { BackupBundleTemplateSectionsItem } from './backupBundleTemplateSectionsItem';
import type { BackupBundleTemplatesItem } from './backupBundleTemplatesItem';
import type { Connector } from './connector';
import type { Doc } from './doc';
import type { DocVersion } from './docVersion';

/**
 * Portable backup format (docs/BACKUP.md). Connector secret fields (per each connector type's schema) are redacted from `configData`; `aiConfig` never includes the provider API key; notification channel config is not included at all.
 */
export interface BackupBundle {
  /** Backup format version; import rejects a mismatch */
  version: number;
  exportedAt: string;
  connectors: Connector[];
  docs: Doc[];
  docVersions: DocVersion[];
  templates: BackupBundleTemplatesItem[];
  templateSections: BackupBundleTemplateSectionsItem[];
  /** Informational only; never applied on import — the encrypted API key can't be restored from a backup */
  aiConfig?: BackupBundleAiConfig;
}
