/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { BackupRunbookStepOperator } from './backupRunbookStepOperator';
import type { RunbookStepKind } from './runbookStepKind';
import type { RunbookStepStoredVerb } from './runbookStepStoredVerb';

/**
 * Stored runbook step as exported in a backup. A bundle written before step kinds existed has no kind or timeoutSeconds; such a step imports as lifecycle.
 */
export interface BackupRunbookStep {
  id: string;
  runbookId: string;
  /** @minimum 0 */
  position: number;
  kind?: RunbookStepKind;
  /**
   * Timeout of a sync_and_wait, wait_until_healthy or wait_for_entity step; 0 or absent means the 300 second default. Not meaningful for lifecycle, config_push and manual steps.
   * @minimum 0
   * @maximum 1800
   */
  timeoutSeconds?: number;
  title: string;
  /** Empty for a manual step. */
  connectorId: string;
  /** Empty for every kind except lifecycle. */
  verb: RunbookStepStoredVerb;
  entityRef: string;
  /** Named action of a connector_action step; empty for every other kind. */
  action?: string;
  /** Configuration field key for config_push steps. */
  fieldKey?: string;
  /** Target value for config_push steps, formatted as JSON text. */
  targetValue?: string;
  /** Entity attribute name for wait_for_entity steps. */
  attribute?: string;
  /** Comparison operator for wait_for_entity steps. */
  operator?: BackupRunbookStepOperator;
  /** Expected attribute value for wait_for_entity steps, formatted as JSON text. */
  expectedValue?: string;
  createdAt: string;
  updatedAt: string;
}
