/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface CertificateExpiry {
  name: string;
  connectorId: string;
  connectorName: string;
  externalId: string;
  /** Active entity identity when reconciliation has run */
  entityId?: string;
  notAfter: string;
  /** Whole days until expiry rounded down, negative after expiry */
  daysLeft: number;
  /** True when the source explicitly reported reachable false */
  unreachable: boolean;
}
