/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ChangeDetailStatus } from './changeDetailStatus';
import type { ChangeSummary } from './changeSummary';
import type { Diff } from './diff';
import type { DocumentDiffProvenance } from './documentDiffProvenance';

export type ChangeDetail = ChangeSummary & {
  status: ChangeDetailStatus;
  diff: Diff;
  affectedDocIds?: string[];
  /** Document-diff provenance. Each entry identifies the changed snapshot field, the template section that rendered it, and the resulting lines in the head revision. Present only when a document diff has source data. */
  provenance?: DocumentDiffProvenance[];
};
