/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export type ComplianceConditionOp =
  (typeof ComplianceConditionOp)[keyof typeof ComplianceConditionOp];

export const ComplianceConditionOp = {
  eq: 'eq',
  neq: 'neq',
  contains: 'contains',
  not_contains: 'not_contains',
  regex: 'regex',
  exists: 'exists',
  gt: 'gt',
  lt: 'lt',
  days_left_lt: 'days_left_lt',
  days_left_gt: 'days_left_gt',
} as const;
