/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ComplianceSchemaAttributes } from './complianceSchemaAttributes';

export interface ComplianceSchema {
  /** Attribute specs by connector type, then entity kind */
  attributes: ComplianceSchemaAttributes;
  /** Typed entity fields a related clause can join on; a catalog attribute is joined as "attributes.<name>" */
  joinFields: string[];
}
