/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ComplianceCondition } from './complianceCondition';
import type { ComplianceRelatedClause } from './complianceRelatedClause';
import type { Severity } from './severity';

export interface ComplianceRuleInput {
  name: string;
  connectorType: string;
  entityKind: string;
  /** @minItems 1 */
  conditions: ComplianceCondition[];
  /**
   * Clauses ANDed against entities of other connectors. A source entity violates when a requires clause finds no related entity or a forbids clause finds one.
   * @maxItems 5
   */
  related?: ComplianceRelatedClause[];
  severity: Severity;
  title: string;
  remediationLink?: string;
  enabled?: boolean;
}
