/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * One field a connector exposes for config-push (ADR 0003).
 */
export interface ConfigField {
  key: string;
  label: string;
  /** Reuses the SchemaField Type vocabulary (text, number, toggle, select, ...). */
  type: string;
  /** true if per-entity (requires entityRef), false if connector-global. */
  entityScope: boolean;
}
