/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectorCategory } from './connectorCategory';
import type { ConnectorUpdateConfig } from './connectorUpdateConfig';

export interface ConnectorUpdate {
  name?: string;
  /** @nullable */
  owner?: string | null;
  url?: string;
  verifyTls?: boolean;
  /** Changing the category requires an instance admin (403 otherwise); resending the stored value is allowed. For a type that derives its category (`custom`), a value different from the derived one is rejected with 400, and a change of the derived category through the configuration also requires an instance admin */
  category?: ConnectorCategory;
  /** Replaces the stored config. Secret fields and `textarea` fields (such as a custom connector recipe) are kept when omitted and cleared by an explicit empty string. For `tlsprobe` connectors all three endpoint settings (`targets`, `import_connector_id`, `import_port`) are kept when omitted, an explicit empty string clears one, and changing them requires an instance admin */
  config?: ConnectorUpdateConfig;
  /**
   * Auto-sync cadence in seconds; null disables scheduled sync (manual only)
   * @nullable
   */
  scheduleSeconds?: number | null;
  /**
   * Optional operator-set credential expiry (RFC3339); null clears it
   * @nullable
   */
  userExpiresAt?: string | null;
  /**
   * Overrides the global rotation.max_age_days for this connector; null clears the override
   * @minimum 1
   * @nullable
   */
  rotationMaxAgeDays?: number | null;
}
