/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectorCategory } from './connectorCategory';
import type { ServiceStatus } from './serviceStatus';

export interface Connector {
  id: string;
  /** matches ServiceSnapshot.ServiceName */
  name: string;
  /** @nullable */
  owner?: string | null;
  category: ConnectorCategory;
  /** e.g. proxmox, portainer, pfsense */
  type: string;
  enabled: boolean;
  status: ServiceStatus;
  url?: string;
  verifyTls?: boolean;
  /**
   * RFC 3339 timestamp of the last completed sync, or the empty string when the connector has never synced.
   * @pattern ^$|^[0-9]{4}-[0-9]{2}-[0-9]{2}T
   */
  lastSyncAt?: string;
  statusMessage?: string;
  /**
   * Auto-sync cadence in seconds; null disables scheduled sync (manual only)
   * @nullable
   */
  scheduleSeconds?: number | null;
  /**
   * RFC 3339 timestamp of the next scheduled sync, or the empty string when no sync is scheduled (manual-only connectors).
   * @pattern ^$|^[0-9]{4}-[0-9]{2}-[0-9]{2}T
   */
  nextRunAt?: string;
  /** @nullable */
  lastSyncDurationMs?: number | null;
  lastSyncError?: string;
  /** Consecutive sync failures since the last success; resets to 0 on success */
  retryCount?: number;
  /**
   * RFC 3339 timestamp when the stored credentials expire, or the empty string when they have no known expiry.
   * @pattern ^$|^[0-9]{4}-[0-9]{2}-[0-9]{2}T
   */
  credentialExpiresAt?: string;
  /** Read-only. When a secret-typed config field was last actually changed; set on create too */
  secretRotatedAt?: string;
  /**
   * Optional operator-set expiry the credential_rotation check treats as an upper bound on the due date: an RFC 3339 timestamp, or the empty string when unset.
   * @pattern ^$|^[0-9]{4}-[0-9]{2}-[0-9]{2}T
   */
  userExpiresAt?: string;
  /**
   * Overrides the global rotation.max_age_days for this connector; null uses the global default
   * @nullable
   */
  rotationMaxAgeDays?: number | null;
}
