/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectorCategory } from './connectorCategory';
import type { ConnectorCreateConfig } from './connectorCreateConfig';

export interface ConnectorCreate {
  name: string;
  /** @nullable */
  owner?: string | null;
  category: ConnectorCategory;
  type: string;
  /** Required unless the connector type's schema marks its `url` field optional (for example Caddy in pasted config_json mode); an empty value is rejected with 400 for types that require it. */
  url?: string;
  verifyTls?: boolean;
  /** Schema-driven fields incl. secrets; stored encrypted, never in plaintext config (ARCHITECTURE.md) */
  config: ConnectorCreateConfig;
  /**
   * Optional operator-set credential expiry (RFC3339)
   * @nullable
   */
  userExpiresAt?: string | null;
  /**
   * Overrides the global rotation.max_age_days for this connector
   * @minimum 1
   * @nullable
   */
  rotationMaxAgeDays?: number | null;
}
