/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectorUpdateConfig } from './connectorUpdateConfig';

export interface ConnectorUpdate {
  name?: string;
  /** @nullable */
  owner?: string | null;
  url?: string;
  verifyTls?: boolean;
  config?: ConnectorUpdateConfig;
  /**
   * Auto-sync cadence in seconds; null disables scheduled sync (manual only)
   * @nullable
   */
  scheduleSeconds?: number | null;
  /**
   * Optional operator-set credential expiry (RFC3339); null clears it
   * @nullable
   */
  userExpiresAt?: string | null;
  /**
   * Overrides the global rotation.max_age_days for this connector; null clears the override
   * @minimum 1
   * @nullable
   */
  rotationMaxAgeDays?: number | null;
}
