/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectorCapabilities } from './connectorCapabilities';
import type { ConnectorCategory } from './connectorCategory';
import type { ConnectorTypeSchemaLifecycleVerbsItem } from './connectorTypeSchemaLifecycleVerbsItem';
import type { SchemaField } from './schemaField';

export interface ConnectorTypeSchema {
  category: ConnectorCategory;
  type: string;
  displayName: string;
  fields: SchemaField[];
  /** True for connector types with no real implementation yet (Fetch/Validate always fail). The UI should mark the type as coming soon and hide/disable Test connection, Sync, and data-viewing actions for it. */
  stub?: boolean;
  /** Health-check latency (ms) above which this connector type reports "degraded" instead of "online". Omitted/zero means use the server's global default. */
  degradedLatencyThresholdMs?: number;
  /** True if this type's credentials refresh automatically (e.g. OAuth2). The credential_rotation quality check always skips it, and the UI should hide the rotation reminder fields on its connector form. */
  isCredentialRefresher?: boolean;
  /** The lifecycle verbs (restart/start/stop) this type's connector implementation supports, e.g. for filtering the runbook step editor's verb picker to what a chosen connector can actually do. */
  lifecycleVerbs?: ConnectorTypeSchemaLifecycleVerbsItem[];
  capabilities: ConnectorCapabilities;
}
