/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectorBulkSyncItemResultStatus } from './connectorBulkSyncItemResultStatus';

export interface ConnectorBulkSyncItemResult {
  id: string;
  status: ConnectorBulkSyncItemResultStatus;
  /** Present when status is success — the async sync job's ID (see SyncJobRef). */
  jobId?: string;
  /** Present when status is error, e.g. not_found. */
  reason?: string;
}
