/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Who owns the connector's settings. `config`: declared in config.yaml and reconciled at startup, so edits, enable/disable and delete are rejected with 409. `config-orphaned`: its config entry was removed; it is disabled and can only be deleted or released.
 */
export type ConnectorManagedBy = (typeof ConnectorManagedBy)[keyof typeof ConnectorManagedBy];

export const ConnectorManagedBy = {
  ui: 'ui',
  config: 'config',
  'config-orphaned': 'config-orphaned',
} as const;
