/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Replaces the stored config. Secret fields and `textarea` fields (such as a custom connector recipe) are kept when omitted and cleared by an explicit empty string. For `tlsprobe` connectors all three endpoint settings (`targets`, `import_connector_id`, `import_port`) are kept when omitted, an explicit empty string clears one, and changing them requires an instance admin
 */
export type ConnectorUpdateConfig = { [key: string]: unknown };
