/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosticsBundleRecentFailuresDeliveriesItemStatus } from './diagnosticsBundleRecentFailuresDeliveriesItemStatus';
import type { NotificationChannelType } from './notificationChannelType';

/**
 * Delivery attempt record only — never the channel's own config
 */
export type DiagnosticsBundleRecentFailuresDeliveriesItem = {
  id?: string;
  notificationId?: string;
  channel?: NotificationChannelType;
  status?: DiagnosticsBundleRecentFailuresDeliveriesItemStatus;
  attempts?: number;
  lastError?: string;
  nextAttemptAt?: string;
  createdAt?: string;
  updatedAt?: string;
};
