/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosticsBundleRecentFailures } from './diagnosticsBundleRecentFailures';
import type { DiagnosticsBundleSanitizedConfig } from './diagnosticsBundleSanitizedConfig';
import type { DiagnosticsBundleVersions } from './diagnosticsBundleVersions';
import type { Health } from './health';

/**
 * Sanitized support bundle (docs/DIAGNOSTICS.md). Connector secret fields are redacted the same way as the backup bundle; notification channel config, OIDC client secrets, and the AI provider API key are never included.
 */
export interface DiagnosticsBundle {
  generatedAt: string;
  health: Health;
  versions: DiagnosticsBundleVersions;
  sanitizedConfig: DiagnosticsBundleSanitizedConfig;
  recentFailures: DiagnosticsBundleRecentFailures;
}
