/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosticsBundleSanitizedConfigAiConfig } from './diagnosticsBundleSanitizedConfigAiConfig';
import type { DiagnosticsBundleSanitizedConfigAuthProviders } from './diagnosticsBundleSanitizedConfigAuthProviders';
import type { DiagnosticsBundleSanitizedConfigConnectorsItem } from './diagnosticsBundleSanitizedConfigConnectorsItem';

export type DiagnosticsBundleSanitizedConfig = {
  connectors?: DiagnosticsBundleSanitizedConfigConnectorsItem[];
  /** cron expression */
  syncSchedule?: string;
  authProviders?: DiagnosticsBundleSanitizedConfigAuthProviders;
  /** Same shape as BackupBundle.aiConfig */
  aiConfig?: DiagnosticsBundleSanitizedConfigAiConfig;
};
