/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DiffFormat } from './diffFormat';
import type { DiffHunksItem } from './diffHunksItem';
import type { DiffLanguage } from './diffLanguage';

/**
 * Generic diff consumed by the unified DiffViewer (§8.2). Two shapes keyed by `format`:
 *   - `infra`: structured key-path before/after rows → `hunks`.
 *   - `doc`: full before/after document revisions → `baseText`/`headText`;
 *     the frontend computes the line + word diff (JetBrains-IDE style).
 * `hunks` is therefore required only for `infra`; `baseText`/`headText` only for `doc`.
 */
export interface Diff {
  /** Picks the DiffViewer formatter */
  format: DiffFormat;
  /** infra format only — per-path before/after rows */
  hunks?: DiffHunksItem[];
  /** doc format only — full text of the "before" revision */
  baseText?: string;
  /** doc format only — full text of the "after" revision */
  headText?: string;
  /** doc format — label for the before revision, e.g. "rev 11" */
  baseLabel?: string;
  /** doc format — label for the after revision, e.g. "rev 12" */
  headLabel?: string;
  /** doc format — content hint; raw-text render for v1 */
  language?: DiffLanguage;
}
