/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DiscoveryCandidate } from './discoveryCandidate';
import type { DiscoveryScanState } from './discoveryScanState';

/**
 * The running or most recent network scan (in memory only, see GET /discovery/scan).
 */
export interface DiscoveryScan {
  id: string;
  /** The scanned IPv4 range with host bits masked */
  cidr: string;
  state: DiscoveryScanState;
  startedAt: string;
  /** Absent while the scan is running */
  endedAt?: string;
  /** Addresses finished */
  done: number;
  /** Addresses in the range */
  total: number;
  /** Addresses where any listed port accepted a connection */
  answered: number;
  /** True when the 60 s deadline cut the scan short */
  partial: boolean;
  candidates: DiscoveryCandidate[];
}
