/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DiscoveryCandidate } from './discoveryCandidate';

/**
 * Payload of WebSocket event discovery.candidate, sent once per candidate as it is found. Per-user: only the admin who started the scan receives it.
 */
export interface DiscoveryCandidateEvent {
  scanId: string;
  candidate: DiscoveryCandidate;
}
