/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Payload of WebSocket event discovery.progress. Sent a few times per second at most, and once when the last address finishes. Per-user: only the admin who started the scan receives it.
 */
export interface DiscoveryProgressEvent {
  scanId: string;
  done: number;
  total: number;
  answered: number;
}
