/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * A product confirmed on the scanned network.
 */
export interface DiscoveryCandidate {
  /** Connector type */
  type: string;
  /** Display name */
  name: string;
  /** IPv4 address */
  address: string;
  port: number;
  /** Connector URL to prefill */
  url: string;
  /** Config field the url goes in: url, or host for Docker */
  urlField: string;
  /** Set when a connector of the same type already points at this address and port */
  connectorId?: string;
}
