/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DiscoveryRateLimitedCode } from './discoveryRateLimitedCode';
import type { DiscoveryRateLimitedDetails } from './discoveryRateLimitedDetails';

/**
 * Body of 429 rate_limited. The Retry-After header carries the same delay.
 */
export interface DiscoveryRateLimited {
  code: DiscoveryRateLimitedCode;
  message: string;
  details: DiscoveryRateLimitedDetails;
}
