/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DiscoveryScan } from './discoveryScan';
import type { DiscoveryScanConflictCode } from './discoveryScanConflictCode';

/**
 * Body of 409 scan_in_progress: the Error envelope's code and message, plus the running scan at the top level (there is no `details`).
 */
export interface DiscoveryScanConflict {
  code: DiscoveryScanConflictCode;
  message: string;
  scan: DiscoveryScan;
}
