/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DocAttachment } from './docAttachment';
import type { DocKind } from './docKind';
import type { DocOrigin } from './docOrigin';

export interface Doc {
  docId: string;
  title: string;
  kind: DocKind;
  /** @nullable */
  serviceId?: string | null;
  parentId?: string;
  /** Empty for active docs; UTC deletion batch timestamp otherwise */
  deletedAt?: string;
  createdBy?: string;
  createdAt?: string;
  /** Markdown body. Sync-owned sections are wrapped in `<!-- wl:gen key="…" h="…" -->` … `<!-- /wl:gen -->` comment markers; everything outside them is human-owned. */
  content: string;
  currentVersion: number;
  updatedAt: string;
  /** generated docs have their marked sections refreshed by sync; human docs are never touched by sync */
  origin?: DocOrigin;
  /** Template the doc is rendered through on sync; empty for the plain snapshot render */
  templateId?: string;
  attachments?: DocAttachment[];
  /** Unresolved or ambiguous wikilinks kept as text during creation or save; content contains resolved Markdown links. */
  linkWarnings?: string[];
  /** RFC3339 time sync last merged this doc; empty if never */
  lastSyncedAt?: string;
}
