/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface DocCreate {
  /**
   * @minLength 1
   * @maxLength 500
   */
  title: string;
  /** Empty or omitted for lab scope */
  serviceId?: string;
  /** Same-scope active parent; omitted for root */
  parentId?: string;
  content?: string;
}
