/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DocEditProposalStatus } from './docEditProposalStatus';

export interface DocEditProposal {
  id: string;
  docId: string;
  docTitle: string;
  /** Empty for lab-wide docs */
  serviceId?: string;
  /** Doc version the proposal was written against */
  baseVersion: number;
  /** Proposed replacement body */
  content: string;
  summary: string;
  authorId: string;
  status: DocEditProposalStatus;
  reviewerId?: string;
  reviewedAt?: string;
  createdAt: string;
}
