/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DocImportIssue } from './docImportIssue';
import type { DocImportNode } from './docImportNode';
import type { DocImportPreviewCollisionsItem } from './docImportPreviewCollisionsItem';
import type { DocImportPreviewMappingsItem } from './docImportPreviewMappingsItem';

export interface DocImportPreview {
  id: string;
  expiresAt: string;
  tree: DocImportNode[];
  docCount: number;
  attachmentCount: number;
  mappings: DocImportPreviewMappingsItem[];
  warnings: DocImportIssue[];
  skipped: DocImportIssue[];
  collisions: DocImportPreviewCollisionsItem[];
}
