/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface DocImportNode {
  docId: string;
  title: string;
  /** Archive path of the note or folder */
  path: string;
  /** Empty for lab docs */
  serviceId: string;
  folder: boolean;
  attachmentCount: number;
  children: DocImportNode[];
}
