/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * generated docs have their marked sections refreshed by sync; human docs are never touched by sync
 */
export type DocOrigin = (typeof DocOrigin)[keyof typeof DocOrigin];

export const DocOrigin = {
  generated: 'generated',
  human: 'human',
} as const;
