/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DocPullRequestSource } from './docPullRequestSource';

export interface DocPullRequest {
  source: DocPullRequestSource;
  /** Installation base URL without userinfo or query */
  url: string;
  /** BookStack token ID: required for bookstack, unused for wikijs */
  tokenId?: string;
  /** BookStack token secret, or the Wiki.js API key */
  tokenSecret: string;
  skipTlsVerify?: boolean;
}
