/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface DocumentDiffProvenance {
  /** JSON-style path of the snapshot field that changed. */
  snapshotPath: string;
  /** Title of the template section that rendered the field. */
  templateSection: string;
  /**
   * Changed line numbers in Diff.headText.
   * @minItems 1
   * @items.minimum 1
   */
  diffLines: number[];
}
