/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { WebAuthnResponse } from './webAuthnResponse';

/**
 * One of `password` (no confirmed factor) or `totp`/`recoveryCode` (confirmed factor) proves the caller's identity for step-up; see GET /auth/elevate/methods.
 */
export interface ElevationRequest {
  /** The elevation action being requested, e.g. "connector.delete", "user.delete" */
  action: string;
  /** ID of the resource the token is bound to, for actions on one (the user for `user.delete`, `user.resetPassword`, `user.resetMfa`, `user.update`; the provider for `authProvider.toggle`, the runbook for `runbook.run`, the run for `runbook.approve`). The token is also bound to the caller's session and is single-use. */
  target?: string;
  password?: string;
  /** 6-digit TOTP code when 2FA is configured */
  totp?: string;
  /** A single-use recovery code, used instead of totp */
  recoveryCode?: string;
  webauthn?: WebAuthnResponse;
}
