/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { WebAuthnResponse } from './webAuthnResponse';

/**
 * One of `password` (no confirmed factor) or `totp`/`recoveryCode` (confirmed factor) proves the caller's identity for step-up; see GET /auth/elevate/methods.
 */
export interface ElevationRequest {
  /** The elevation action being requested, e.g. "connector.delete", "user.delete" */
  action: string;
  password?: string;
  /** 6-digit TOTP code when 2FA is configured */
  totp?: string;
  /** A single-use recovery code, used instead of totp */
  recoveryCode?: string;
  webauthn?: WebAuthnResponse;
}
