/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { Error } from './error';

/**
 * Elevation required — the operation needs step-up (the instance step-up setting is on, or always for MFA management) and the request carried no X-Elevation-Token header. Client should call POST /auth/elevate and retry. Error.code = `elevation_required`. A token that is invalid, expired, already used, or issued for a different action, target, user or session returns 401 `unauthorized` instead.
 */
export type ElevationRequiredResponse = Error;
