/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { EntityFinding } from './entityFinding';
import type { EntityHistoryChange } from './entityHistoryChange';
import type { EntityLink } from './entityLink';
import type { EntityMember } from './entityMember';
import type { EntityNeighbor } from './entityNeighbor';
import type { EntityRunbook } from './entityRunbook';

export interface EntityDetail {
  id: string;
  kind: string;
  name: string;
  gone: boolean;
  members: EntityMember[];
  relatedByIp: EntityLink[];
  neighbors: EntityNeighbor[];
  history: EntityHistoryChange[];
  findings: EntityFinding[];
  onReportingConnectors: EntityFinding[];
  runbooks: EntityRunbook[];
}
