/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { EntityIdentityOverrideRecordAction } from './entityIdentityOverrideRecordAction';

/**
 * Stored override as exported in a backup; a merge pair is in sorted member-key order
 */
export interface EntityIdentityOverrideRecord {
  id: string;
  action: EntityIdentityOverrideRecordAction;
  connectorId: string;
  kind: string;
  ref: string;
  otherConnectorId?: string;
  otherKind?: string;
  otherRef?: string;
  note: string;
  createdBy: string;
  createdAt: string;
}
