/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { EntityOverrideCreateAction } from './entityOverrideCreateAction';

export interface EntityOverrideCreate {
  action: EntityOverrideCreateAction;
  connectorId: string;
  kind: string;
  ref: string;
  /** Required for a merge, forbidden for a detach */
  otherConnectorId?: string;
  /** Must equal kind */
  otherKind?: string;
  otherRef?: string;
  /** @maxLength 1000 */
  note?: string;
}
