/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { EntityOverrideAction } from './entityOverrideAction';
import type { EntityOverrideMember } from './entityOverrideMember';
import type { EntityOverrideState } from './entityOverrideState';

export interface EntityOverride {
  id: string;
  action: EntityOverrideAction;
  note: string;
  /** ID of the administrator who created it */
  createdBy: string;
  createdAt: string;
  state: EntityOverrideState;
  /** One member for a detach, two for a merge */
  members: EntityOverrideMember[];
}
