/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { CursorParameter } from './cursorParameter';

export type GetConnectorsConnectorIdSnapshotsParams = {
  /**
   * @maximum 100
   */
  limit?: number;
  /**
   * Opt in to keyset (cursor) pagination, which stays cheap as the table grows. Send it empty for the first page, then echo back the previous response's `nextCursor` (or `X-Next-Cursor` header, where the response body is a bare array). The value is opaque and must not be constructed by clients. Omit the parameter entirely for offset pagination, whose behaviour is unchanged; `page` is ignored while a cursor is in use.
   */
  cursor?: CursorParameter;
};
