/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * How the grant was created; see the endpoint description.
 */
export type GetConnectorsConnectorIdPermissions200ItemSource =
  (typeof GetConnectorsConnectorIdPermissions200ItemSource)[keyof typeof GetConnectorsConnectorIdPermissions200ItemSource];

export const GetConnectorsConnectorIdPermissions200ItemSource = {
  manual: 'manual',
  oidc: 'oidc',
  config: 'config',
} as const;
