/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { PageParameter } from './pageParameter';
import type { PageSizeParameter } from './pageSizeParameter';
import type { Severity } from './severity';

export type GetRunbooksParams = {
  /**
   * Filter to runbooks targeting this change type, e.g. vm.created. Mutually exclusive with alertSeverity and findingCheckType.
   */
  changeType?: string;
  /**
   * Filter to runbooks targeting this alert severity. Mutually exclusive with changeType and findingCheckType.
   */
  alertSeverity?: Severity;
  /**
   * Filter to runbooks targeting this quality finding check type, e.g. stale. Mutually exclusive with changeType and alertSeverity.
   */
  findingCheckType?: string;
  /**
   * @minimum 1
   */
  page?: PageParameter;
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: PageSizeParameter;
};
