/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { GetSearchType } from './getSearchType';

export type GetSearchParams = {
  /**
   * @maxLength 500
   */
  q?: string;
  type?: GetSearchType;
  /**
   * @maxLength 128
   */
  connector?: string;
  /**
   * @maxLength 100
   */
  kind?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
