/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { TopologyPathStep } from './topologyPathStep';

export type GetTopologyPath200 = {
  found: boolean;
  /**
   * Edge count of the shortest path; present only when to is given.
   * @minimum 0
   */
  hops?: number;
  /** True when a directed walk (no to) hit the 1000-step cap. */
  truncated: boolean;
  path: TopologyPathStep[];
};
