/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { JobInfoLastStatus } from './jobInfoLastStatus';

export interface JobInfo {
  /** Job name, e.g. "quality", "sync", "backup", "docexport" */
  name: string;
  /** 5-field or 6-field (with leading seconds) cron expression */
  cronExpr: string;
  /** Absent if the job has never run yet */
  lastStatus?: JobInfoLastStatus;
  /** Error from the most recent failing run; empty when lastStatus is ok */
  lastError?: string;
  /** Absent if the job has never run yet */
  lastRunAt?: string;
  /** Absent if the job has never succeeded */
  lastSuccessAt?: string;
  /** Absent if the job has never failed */
  lastFailureAt?: string;
  /** Next scheduled run per the live cron entry */
  nextRunAt?: string;
}
