/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface JournalEntryInput {
  /**
   * @minLength 1
   * @maxLength 50000
   */
  body: string;
  /** Defaults to now; supports backdated entries */
  occurredAt?: string;
  /** @maxLength 128 */
  connectorId?: string;
  /** @maxLength 128 */
  docId?: string;
  /** @maxLength 100 */
  entityKind?: string;
  /** @maxLength 500 */
  entityName?: string;
  /** @maxLength 2048 */
  entityRef?: string;
}
