/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { NotificationChannelType } from './notificationChannelType';
import type { Severity } from './severity';

export interface NotificationRoute {
  /** Event type the route applies to. Emitted today: alert.created, finding.created, system.job_failed (scheduled job failing/recovered), runbook.run_failed (failed run), runbook.run_waiting (manual confirmation), runbook.run_approval_requested (eligible second operators). */
  eventType: string;
  channel: NotificationChannelType;
  enabled: boolean;
  minSeverity?: Severity;
  /** Optional connector category filter; empty/absent matches any category. */
  connectorCategory?: string;
  /** Optional connector ID filter; empty/absent matches any connector. */
  connectorId?: string;
}
