/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Channel-specific, keyed by type (see docs/NOTIFICATIONS.md for the full field reference per channel):
 *   - webhook: { url, secret } — generic JSON POST, HMAC-signed when a secret is set.
 *   - discord / slack: { url, secret } — incoming-webhook URL; secret HMAC-signs the
 *     request the same way the generic webhook channel does.
 *   - ntfy: { url (server, default https://ntfy.sh), topic, priority, tags } — publishes
 *     via ntfy's HTTP API.
 *   - telegram: { chatId, secret } — secret is the bot token; sends via the Bot API's
 *     sendMessage.
 *   - smtp: { host, port, username, secret, from, to } — secret is the SMTP password;
 *     sent with opportunistic STARTTLS.
 * "secret" is write-only: webhook/Discord/Slack sign deliveries with HMAC-SHA256 (X-WiseLabz-Timestamp and X-WiseLabz-Signature headers) when set; Telegram and SMTP reuse the same field for their own credential (bot token / password). It is stored encrypted and never returned; reads expose secretSet instead.
 */
export type NotificationChannelConfig = { [key: string]: unknown };
