/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { OidcProviderSource } from './oidcProviderSource';

/**
 * File/env-defined provider, surfaced read-only. issuerUrl, clientId, and the secret are never accepted or returned over the API; `secretConfigured` only signals whether the secret is present in config.
 */
export interface OidcProvider {
  id: string;
  displayName: string;
  readonly issuerUrl: string;
  readonly clientId: string;
  readonly secretConfigured: boolean;
  /** The one mutable flag (via PUT /auth/providers/{providerId}/enabled) */
  enabled: boolean;
  readonly source: OidcProviderSource;
  readonly scopes?: readonly string[];
}
