/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export type PostAuthElevateOidcBeginBody = {
  /** The elevation action being requested, e.g. connector.delete */
  action: string;
  /** ID of the resource the token is bound to, for actions on one (e.g. the user for user.delete) */
  target?: string;
};
