/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export type PostConnectorsConnectorIdConfigPushBody = {
  /** Target entity ref, required when the field's ConfigField.entityScope is true. */
  entityRef?: string;
  fieldKey: string;
  value: unknown;
  /** The field's currently-displayed value (read from GET /{connectorId}/data before editing), used to revert if the push doesn't verify. */
  previousValue?: unknown;
};
