/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export type PostConnectorsConnectorIdStopBody = {
  /** Target entity's SnapshotEntity.externalId, or omitted for connectors that manage a single implicit service. Also honored for dry-run previews: when set and it matches an entity in the latest snapshot, the preview's targetService is that entity's name. */
  entityRef?: string;
};
