/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export type QualityCheckType = (typeof QualityCheckType)[keyof typeof QualityCheckType];

export const QualityCheckType = {
  stale: 'stale',
  empty: 'empty',
  failing: 'failing',
  ownership_incomplete: 'ownership_incomplete',
  credential_rotation: 'credential_rotation',
  compliance: 'compliance',
  config_drift: 'config_drift',
} as const;
