/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RecipePreviewInputConfig } from './recipePreviewInputConfig';

export interface RecipePreviewInput {
  /** Existing custom connector whose stored credentials may be reused */
  connectorId?: string;
  url: string;
  verifyTls?: boolean;
  /** Custom connector configuration including the recipe and optional credentials */
  config: RecipePreviewInputConfig;
}
