/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ReportRotationEntry } from './reportRotationEntry';

export interface ReportRotationsSection {
  error?: string;
  /** Connectors whose secretRotatedAt fell inside the window. */
  rotated: ReportRotationEntry[];
  /** Connectors with an open, overdue credential_rotation finding as of now. */
  overdue: ReportRotationEntry[];
  /** Connectors with an open credential_rotation finding due soon (not yet overdue) as of now. */
  dueSoon: ReportRotationEntry[];
}
