/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ReportDefinitionSummary } from './reportDefinitionSummary';
import type { ReportSections } from './reportSections';

/**
 * The typed JSON payload stored on a report row; also what Markdown/HTML are rendered from.
 */
export interface ReportData {
  definition: ReportDefinitionSummary;
  periodStart: string;
  periodEnd: string;
  /** True when the window exceeded the 31-day cap and was clamped (plan Q22). */
  truncated: boolean;
  sections: ReportSections;
}
