/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ReportComplianceSection } from './reportComplianceSection';
import type { ReportDocsSection } from './reportDocsSection';
import type { ReportDriftSection } from './reportDriftSection';
import type { ReportJobsSection } from './reportJobsSection';
import type { ReportQualitySection } from './reportQualitySection';
import type { ReportRotationsSection } from './reportRotationsSection';

export interface ReportSections {
  docs: ReportDocsSection;
  compliance: ReportComplianceSection;
  rotations: ReportRotationsSection;
  quality: ReportQualitySection;
  drift: ReportDriftSection;
  jobs: ReportJobsSection;
}
