/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { QualityCheckType } from './qualityCheckType';
import type { QualityFindingStatus } from './qualityFindingStatus';
import type { Severity } from './severity';

export interface ReportFindingSummary {
  id: string;
  connectorId: string;
  connectorName: string;
  checkType: QualityCheckType;
  severity: Severity;
  title: string;
  status: QualityFindingStatus;
  detectedAt: string;
  /** @nullable */
  resolvedAt?: string | null;
}
