/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ReportChannelType } from './reportChannelType';
import type { ReportSection } from './reportSection';

export interface ReportDefinition {
  id: string;
  /** Immutable after creation; used in the cron job name `report:<slug>` and in download filenames. */
  slug: string;
  name: string;
  enabled: boolean;
  /** 5-field or 6-field (with leading seconds) cron expression */
  cronExpr: string;
  /** IANA zone name, e.g. "America/New_York". Applied as a CRON_TZ= prefix on cronExpr. */
  timezone: string;
  sections: ReportSection[];
  /** Optional connector filter (plan Q14) applied to every section except job health, which always covers every job. */
  connectorIds: string[];
  channels: ReportChannelType[];
  /** User ID of the operator who created this definition. */
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}
