/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ReportData } from './reportData';
import type { ReportStatus } from './reportStatus';
import type { ReportTrigger } from './reportTrigger';

/**
 * ReportSummary plus the full typed data and rendered Markdown, returned by GET /reports/{reportId}.
 */
export interface Report {
  id: string;
  /** @nullable */
  definitionId: string | null;
  definitionName: string;
  trigger: ReportTrigger;
  periodStart: string;
  periodEnd: string;
  truncated: boolean;
  status: ReportStatus;
  createdAt: string;
  data: ReportData;
  /** Pre-rendered Markdown, stored at generation time. HTML is rendered on demand from `data` instead (see GET /reports/{reportId}/download). */
  markdown: string;
}
