/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Channel TYPES a report definition delivers to (plan Q13) — channels have no IDs; delivery bypasses the normal routing rules and goes straight to every enabled channel of these types.
 */
export type ReportChannelType = (typeof ReportChannelType)[keyof typeof ReportChannelType];

export const ReportChannelType = {
  slack: 'slack',
  discord: 'discord',
  webhook: 'webhook',
} as const;
