/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ReportChangeEntry } from './reportChangeEntry';
import type { ReportConnectorDrift } from './reportConnectorDrift';

export interface ReportDriftSection {
  error?: string;
  /** Total changes detected in the window (optionally filtered by connectorIds). */
  total: number;
  byConnector: ReportConnectorDrift[];
  /**
   * The 10 most severe changes in the window (plan Q19).
   * @maxItems 10
   */
  topChanges: ReportChangeEntry[];
}
