/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ReportStatus } from './reportStatus';
import type { ReportTrigger } from './reportTrigger';

export interface ReportSummary {
  id: string;
  /**
   * Null if the definition was since deleted.
   * @nullable
   */
  definitionId: string | null;
  /** Copied at generation time; stable even if the definition is renamed or deleted. */
  definitionName: string;
  trigger: ReportTrigger;
  periodStart: string;
  periodEnd: string;
  truncated: boolean;
  status: ReportStatus;
  createdAt: string;
}
