/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * One report section, matching internal/report.Sections's fields.
 */
export type ReportSection = (typeof ReportSection)[keyof typeof ReportSection];

export const ReportSection = {
  docs: 'docs',
  compliance: 'compliance',
  rotations: 'rotations',
  quality: 'quality',
  drift: 'drift',
  jobs: 'jobs',
} as const;
