/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RestartPreviewDependentServicesItem } from './restartPreviewDependentServicesItem';

/**
 * Non-mutating preview of the future service.restart action.
 */
export interface RestartPreview {
  targetService: string;
  /** @minimum 0 */
  estimatedDowntimeSeconds: number;
  /** Names of devices the target powers or carries (e.g. the APs and cameras behind a UniFi PoE port); the blast radius of the action. Empty when the target declares none. */
  affectedEntities?: string[];
  dependentServices: RestartPreviewDependentServicesItem[];
}
