/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ResumeRunbookRunBodyDecision } from './resumeRunbookRunBodyDecision';

export type ResumeRunbookRunBody = {
  /** Decision for the unknown connector_action step that a resume would start with. */
  decision?: ResumeRunbookRunBodyDecision;
  /** The step the decision is for. Required with a decision on an unknown connector_action step; must be the run's first non-succeeded step. */
  stepId?: string;
  /** The run's updatedAt exactly as the client received it. Required with a decision on an unknown connector_action step; must equal the run's current updatedAt. */
  updatedAt?: string;
};
