/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

export interface RetentionSettings {
  /** Delete service snapshots older than this many days; 0 disables cleanup for this category */
  snapshotDays: number;
  /** Delete doc revisions older than this many days; 0 disables cleanup for this category */
  docVersionDays: number;
  /** Delete resolved/dismissed alerts older than this many days; 0 disables cleanup for this category */
  alertDays: number;
  /** Delete sync run history older than this many days; 0 disables cleanup for this category */
  syncRunDays: number;
  /** Delete audit log records older than this many days; 0 disables cleanup for this category */
  auditDays: number;
  /** 5-field or 6-field (with leading seconds) cron expression */
  cronExpr: string;
  updatedAt?: string;
}
