/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface RetentionSettings {
  /** Delete service snapshots older than this many days; 0 disables cleanup for this category */
  snapshotDays: number;
  /** Delete doc revisions older than this many days; 0 disables cleanup for this category */
  docVersionDays: number;
  /** Delete resolved/dismissed alerts older than this many days; 0 disables cleanup for this category */
  alertDays: number;
  /** Delete sync run history older than this many days; 0 disables cleanup for this category */
  syncRunDays: number;
  /** Delete audit log records older than this many days; 0 disables cleanup for this category */
  auditDays: number;
  /** Delete health-check time-series rows older than this many days; 0 disables cleanup for this category */
  healthCheckDays: number;
  /**
   * Permanently purge trash older than this many days; 0 disables cleanup
   * @minimum 0
   */
  deletedDocsDays?: number;
  /**
   * Expire unanswered approval requests after this many hours; swept by a per-minute leader job
   * @minimum 1
   * @maximum 8760
   */
  runbookApprovalHours?: number;
  /**
   * Expire open runbook runs after this many hours of inactivity; must be between 1 and 8760
   * @minimum 1
   * @maximum 8760
   */
  runbookOpenRunHours?: number;
  /**
   * Delete finished runbook runs older than this many days; 0 keeps run history forever; must be between 0 and 3650
   * @minimum 0
   * @maximum 3650
   */
  runbookRunDays?: number;
  /** Delete generated reports older than this many days; 0 disables cleanup for this category */
  reportDays: number;
  /** 5-field or 6-field (with leading seconds) cron expression */
  cronExpr: string;
  updatedAt?: string;
}
