/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Two roles (ARCHITECTURE.md 2026-06-27). `viewer` reads docs + live state; `operator` adds every mutating action (sync, connector CRUD, and — for the v1 single-admin homelab — user management). Enforced server-side on every mutating endpoint; UI hiding a control is convenience, never the boundary.
 */
export type Role = (typeof Role)[keyof typeof Role];

export const Role = {
  viewer: 'viewer',
  operator: 'operator',
} as const;
