/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * A lifecycle step's verb; empty for every other step kind and for a redacted step.
 */
export type RunbookStepStoredVerb =
  (typeof RunbookStepStoredVerb)[keyof typeof RunbookStepStoredVerb];

export const RunbookStepStoredVerb = {
  '': '',
  restart: 'restart',
  start: 'start',
  stop: 'stop',
} as const;
