/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export type RunbookRunStepKind = (typeof RunbookRunStepKind)[keyof typeof RunbookRunStepKind];

export const RunbookRunStepKind = {
  lifecycle: 'lifecycle',
  sync_and_wait: 'sync_and_wait',
  wait_until_healthy: 'wait_until_healthy',
  manual: 'manual',
  config_push: 'config_push',
  wait_for_entity: 'wait_for_entity',
  connector_action: 'connector_action',
} as const;
