/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RestartPreview } from './restartPreview';
import type { RunbookRunStepKind } from './runbookRunStepKind';
import type { RunbookRunStepState } from './runbookRunStepState';
import type { RunbookRunStepVerb } from './runbookRunStepVerb';

/**
 * Frozen step and its current outcome. A redacted step carries no kind, title, connector, entity, verb, timeout, error or preview; only identifiers, position, state, times, confirming user and permission flags remain. Manual steps have no connector and are visible.
 */
export interface RunbookRunStep {
  id: string;
  position: number;
  kind?: RunbookRunStepKind;
  title?: string;
  connectorId?: string;
  connectorName?: string;
  verb?: RunbookRunStepVerb;
  entityRef?: string;
  timeoutSeconds?: number;
  state?: RunbookRunStepState;
  startedAt?: string;
  finishedAt?: string;
  error?: string;
  confirmedBy?: string;
  redacted: boolean;
  canExecute: boolean;
  /** Machine code for why canExecute is false; one of no_viewer_grant, no_operator_grant, preview_unavailable. */
  executeBlockedReason?: string;
  preview?: RestartPreview;
}
