/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RunbookStep } from './runbookStep';
import type { RunbookTargetType } from './runbookTargetType';

export interface Runbook {
  id: string;
  title: string;
  body: string;
  targetType: RunbookTargetType;
  /** A changeType value (e.g. vm.created) when targetType=change_type, a Severity value when targetType=alert_severity, or a quality finding check type when targetType=finding_check_type. */
  targetValue: string;
  /**
   * Known-good ServiceSnapshot to point at, if any
   * @nullable
   */
  snapshotId?: string | null;
  /** @nullable */
  docId?: string | null;
  /** Connector lifecycle operations this runbook points at, in position order. Linking a step grants no mutation permission by itself — see canExecute. */
  steps: RunbookStep[];
  createdAt: string;
  updatedAt: string;
}
