/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RunbookStepExecuteBlockedReason } from './runbookStepExecuteBlockedReason';
import type { RunbookStepVerb } from './runbookStepVerb';

export interface RunbookStep {
  id: string;
  /** Order within the runbook, 0-based; matches the steps array index. */
  position: number;
  title: string;
  connectorId: string;
  /** The referenced connector's display name, for rendering without a second lookup. */
  connectorName: string;
  verb: RunbookStepVerb;
  /** Target entity's SnapshotEntity.externalId, or empty for connectors that manage a single implicit service. */
  entityRef: string;
  /** Whether the calling user currently holds at least an operator grant on connectorId. */
  canExecute: boolean;
  /** Empty when canExecute is true; "no_operator_grant" otherwise. */
  executeBlockedReason: RunbookStepExecuteBlockedReason;
}
