/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RunbookTargetType } from './runbookTargetType';

export interface Runbook {
  id: string;
  title: string;
  body: string;
  targetType: RunbookTargetType;
  /** A changeType value (e.g. vm.created) when targetType=change_type, or a Severity value when targetType=alert_severity. */
  targetValue: string;
  /**
   * Known-good ServiceSnapshot to point at, if any
   * @nullable
   */
  snapshotId?: string | null;
  /** @nullable */
  docId?: string | null;
  createdAt: string;
  updatedAt: string;
}
