/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RunbookStepInput } from './runbookStepInput';
import type { RunbookTargetType } from './runbookTargetType';

export interface RunbookUpdate {
  title?: string;
  body?: string;
  targetType?: RunbookTargetType;
  targetValue?: string;
  /** @nullable */
  snapshotId?: string | null;
  /** @nullable */
  docId?: string | null;
  /**
   * Omit this key entirely to leave the runbook's steps unchanged; include it (even as []) to replace all steps.
   * @maxItems 20
   */
  steps?: RunbookStepInput[];
}
