/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RunbookStepVerb } from './runbookStepVerb';

export interface RunbookStepInput {
  /** An existing step's ID, to keep it (and its identity in audit history) across a replace-all update. Omit for a new step, or when creating a runbook; any ID that didn't already belong to this runbook is ignored and a fresh one is generated. */
  id?: string;
  title: string;
  connectorId: string;
  verb: RunbookStepVerb;
  entityRef?: string;
}
