/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RunbookDraftTargetType } from './runbookDraftTargetType';

export interface RunbookDraft {
  title: string;
  /** Markdown template built from the alert and linked change */
  body: string;
  targetType: RunbookDraftTargetType;
  targetValue: string;
  /** Set when a runbook is already bound to the suggested target */
  existingRunbookId?: string;
}
