/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RestartPreview } from './restartPreview';
import type { RunbookRunStepKind } from './runbookRunStepKind';
import type { RunbookRunStepOperator } from './runbookRunStepOperator';
import type { RunbookRunStepState } from './runbookRunStepState';
import type { RunbookRunStepVerb } from './runbookRunStepVerb';

/**
 * Frozen step and its current outcome. A redacted step carries no kind, title, connector, entity, verb, timeout, error or preview, and none of the config-push or entity-wait fields (field key, target value, attribute, operator, expected value, current value); only identifiers, position, state, times, confirming user and permission flags remain. Manual steps have no connector and are visible.
 */
export interface RunbookRunStep {
  id: string;
  position: number;
  kind?: RunbookRunStepKind;
  title?: string;
  connectorId?: string;
  connectorName?: string;
  verb?: RunbookRunStepVerb;
  entityRef?: string;
  /** Configuration field key for config_push steps. */
  fieldKey?: string;
  /** Target value for config_push steps, formatted as JSON text. */
  targetValue?: string;
  /** Entity attribute name for wait_for_entity steps. */
  attribute?: string;
  /** Comparison operator for wait_for_entity steps. */
  operator?: RunbookRunStepOperator;
  /** Expected attribute value for wait_for_entity steps, formatted as JSON text. */
  expectedValue?: string;
  timeoutSeconds?: number;
  /** Current configuration value for config_push steps in a preview. */
  currentValue?: unknown;
  /** Whether the connector could report the current configuration value in a preview. */
  currentValueKnown?: boolean;
  state?: RunbookRunStepState;
  startedAt?: string;
  finishedAt?: string;
  error?: string;
  confirmedBy?: string;
  redacted: boolean;
  canExecute: boolean;
  /** Machine code for why canExecute is false; one of no_viewer_grant, no_operator_grant, preview_unavailable, unsupported_field. */
  executeBlockedReason?: string;
  preview?: RestartPreview;
}
