/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RunbookRunState } from './runbookRunState';
import type { RunbookRunUpdatedEventStep } from './runbookRunUpdatedEventStep';

/**
 * Payload of WebSocket event runbook.run.updated, emitted on every run or step transition, including retention expiry. Connector step events reach only clients permitted to view that connector. Run-level and manual-step events contain no sensitive connector metadata; fetch the run detail to apply redaction.
 */
export interface RunbookRunUpdatedEvent {
  runId: string;
  runbookId?: string;
  state: RunbookRunState;
  reason?: string;
  step?: RunbookRunUpdatedEventStep;
}
