/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RunbookStepExecuteBlockedReason } from './runbookStepExecuteBlockedReason';
import type { RunbookStepKind } from './runbookStepKind';
import type { RunbookStepOperator } from './runbookStepOperator';
import type { RunbookStepStoredVerb } from './runbookStepStoredVerb';

export interface RunbookStep {
  id: string;
  /** Order within the runbook, 0-based; matches the steps array index. */
  position: number;
  /** Absent for a step redacted because the caller cannot view its connector. */
  kind?: RunbookStepKind;
  title: string;
  /** Empty for a manual step, and for a step redacted because the caller cannot view its connector. */
  connectorId: string;
  /** The referenced connector's display name, for rendering without a second lookup. */
  connectorName: string;
  verb: RunbookStepStoredVerb;
  /** Target entity's SnapshotEntity.externalId, or empty for connectors that manage a single implicit service. */
  entityRef: string;
  /** Configuration field key for config_push steps. */
  fieldKey?: string;
  /** Target value for config_push steps, formatted as JSON text. */
  targetValue?: string;
  /** Entity attribute name for wait_for_entity steps. */
  attribute?: string;
  /** Comparison operator for wait_for_entity steps. */
  operator?: RunbookStepOperator;
  /** Expected attribute value for wait_for_entity steps, formatted as JSON text. */
  expectedValue?: string;
  /**
   * Timeout of a sync_and_wait, wait_until_healthy or wait_for_entity step, in seconds. Always 0 for lifecycle, config_push and manual steps, whenever the step was created, and for a redacted step.
   * @minimum 0
   * @maximum 1800
   */
  timeoutSeconds: number;
  /** Whether the calling user can execute this step on its own: it is a lifecycle step and they hold at least an operator grant on connectorId. */
  canExecute: boolean;
  /** Empty when canExecute is true; "no_operator_grant" or "no_viewer_grant" when the caller lacks the grant, and "not_lifecycle" for a step whose kind only runs inside a run. */
  executeBlockedReason: RunbookStepExecuteBlockedReason;
}
