/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Empty when canExecute is true; "no_operator_grant" or "no_viewer_grant" when the caller lacks the grant, and "not_lifecycle" for a step whose kind only runs inside a run.
 */
export type RunbookStepExecuteBlockedReason =
  (typeof RunbookStepExecuteBlockedReason)[keyof typeof RunbookStepExecuteBlockedReason];

export const RunbookStepExecuteBlockedReason = {
  '': '',
  no_operator_grant: 'no_operator_grant',
  no_viewer_grant: 'no_viewer_grant',
  not_lifecycle: 'not_lifecycle',
} as const;
