/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * lifecycle restarts, starts or stops a connector (optionally one entity); sync_and_wait syncs a connector and waits for the sync to finish; wait_until_healthy waits until a connector's health check reports online; manual waits for a human to confirm; config_push updates a writable connector configuration field; wait_for_entity waits until an entity's attribute matches an expected value.
 */
export type RunbookStepKind = (typeof RunbookStepKind)[keyof typeof RunbookStepKind];

export const RunbookStepKind = {
  lifecycle: 'lifecycle',
  sync_and_wait: 'sync_and_wait',
  wait_until_healthy: 'wait_until_healthy',
  manual: 'manual',
  config_push: 'config_push',
  wait_for_entity: 'wait_for_entity',
} as const;
