/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export type RunbookRunState = (typeof RunbookRunState)[keyof typeof RunbookRunState];

export const RunbookRunState = {
  running: 'running',
  waiting_manual: 'waiting_manual',
  failed: 'failed',
  succeeded: 'succeeded',
  cancelled: 'cancelled',
  expired: 'expired',
} as const;
