/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RunbookRunState } from './runbookRunState';

export interface RunbookRunRecord {
  id: string;
  /** Omitted after runbook deletion */
  runbookId?: string;
  /** Title frozen at start */
  runbookTitle: string;
  state: RunbookRunState;
  reason?: string;
  startedBy: string;
  resumedBy?: string;
  cancelledBy?: string;
  startedAt: string;
  updatedAt: string;
  finishedAt?: string;
}
