/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RunbookRunState } from './runbookRunState';
import type { RunChangedCode } from './runChangedCode';

/**
 * The 409 body of a resume whose stepId or updatedAt no longer matches the run.
 */
export interface RunChanged {
  code: RunChangedCode;
  message: string;
  state: RunbookRunState;
  updatedAt: string;
}
