/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { SavedViewSurface } from './savedViewSurface';

/**
 * A user's named, reusable filter set for one list surface (docs/SAVED_VIEWS.md).
 */
export interface SavedView {
  id: string;
  userId: string;
  surface: SavedViewSurface;
  name: string;
  /** Opaque JSON blob; the backend never inspects its shape — each frontend list surface owns it. */
  filters: string;
  createdAt: string;
}
