/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { SchemaFieldKind } from './schemaFieldKind';

export interface SchemaField {
  name: string;
  label: string;
  kind: SchemaFieldKind;
  required: boolean;
  /** Rendered as password input; write-only */
  secret?: boolean;
  placeholder?: string;
  description?: string;
  /** Regexp a text/password value must match */
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  /** Allowed values of a select field */
  options?: string[];
}
