/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { SchemaFieldKind } from './schemaFieldKind';
import type { SchemaFieldOptionsItem } from './schemaFieldOptionsItem';

export interface SchemaField {
  name: string;
  label: string;
  kind: SchemaFieldKind;
  required: boolean;
  /** Rendered as password input; write-only */
  secret?: boolean;
  placeholder?: string;
  options?: SchemaFieldOptionsItem[];
}
