/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { TemplateSchemaFields } from './templateSchemaFields';
import type { TemplateSchemaFunctionsItem } from './templateSchemaFunctionsItem';

/**
 * Free-form reference for the template editor: available templateData field paths/types and the list of filter functions usable in `{{ .Field | fn }}` pipelines. Shape mirrors backend doc.templatefuncs and connector.ServiceSnapshot — not strictly typed since it's editor-reference-only.
 */
export interface TemplateSchema {
  fields?: TemplateSchemaFields;
  functions?: TemplateSchemaFunctionsItem[];
}
