/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { TimelineNarrationSourceKind } from './timelineNarrationSourceKind';

export interface TimelineNarrationSource {
  /** Citation number used as [n] in the narration */
  n: number;
  kind: TimelineNarrationSourceKind;
  id: string;
  docId: string;
  connectorId: string;
  timestamp: string;
  title: string;
}
