/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { TimelineNarrationSource } from './timelineNarrationSource';

export interface TimelineNarration {
  /** Plain text, empty when the window has no visible events */
  narration: string;
  /** The events that entered the prompt, numbered oldest first */
  sources: TimelineNarrationSource[];
  /** Normalized lower bound of the window, empty when unbounded */
  after: string;
  /** Normalized upper bound of the window, empty when unbounded */
  before: string;
  /** Events included in the prompt */
  eventCount: number;
  /** Visible events matching the filter */
  totalEvents: number;
  /** True when the oldest events were left out */
  truncated: boolean;
  provider: string;
  fallbackUsed: boolean;
}
