/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface TopologyPathStep {
  connectorId: string;
  connectorName: string;
  kind: string;
  name: string;
  /** Matching graph node ID, including the resolved identity when available. */
  nodeId?: string;
  /** Graph node ID of the step this one was reached from (resolved like nodeId, from active members on viewable connectors only); absent on start nodes. With edgeKind it identifies the traversed edge. */
  fromNodeId?: string;
  /** True when the edge into this step was traversed against its direction (only possible for the undirected path to a target). */
  edgeReversed?: boolean;
  edgeKind?: string;
  edgeSource?: string;
  detail?: string;
}
