/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { MfaFactor } from './mfaFactor';

export interface TotpConfirmResult {
  factor: MfaFactor;
  /** Present only on the user's first confirmed factor; shown once. */
  recoveryCodes?: string[];
  /** Present only when the caller's prior session was enrollment-only. */
  accessToken?: string;
  /** Access token TTL in seconds */
  expiresIn?: number;
}
