/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface UptimeWindowStats {
  windowStart: string;
  windowEnd: string;
  /** Number of health checks that contributed measured (non-maintenance) time in this window; 0 means no data and availabilityPct is meaningless */
  checkCount: number;
  /** Time-weighted % of measured time spent in a non-offline status (a status is only extrapolated a bounded time past its check); 0 when checkCount is 0 */
  availabilityPct: number;
  /** Mean time to recovery, in seconds, over outages that both started and recovered inside the window; 0 when there were none. */
  mttrSeconds: number;
  /** Number of resolved outages the mttrSeconds mean is over */
  outageCount: number;
}
