/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

export interface UptimeWindowStats {
  windowStart: string;
  windowEnd: string;
  /** Number of health_checks rows in this window */
  checkCount: number;
  /** Time-weighted % of the window spent in a non-offline status; 0 when checkCount is 0 */
  availabilityPct: number;
  /** Mean time to recovery, in seconds, over outages that both started and recovered inside the window; 0 when there were none. */
  mttrSeconds: number;
  /** Number of resolved outages the mttrSeconds mean is over */
  outageCount: number;
}
