/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with each other.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { UserAuthSource } from './userAuthSource';
import type { UserDigestCadence } from './userDigestCadence';
import type { UserRole } from './userRole';

export interface User {
  id: string;
  username: string;
  displayName?: string;
  email?: string;
  role: UserRole;
  authSource: UserAuthSource;
  disabled?: boolean;
  /** When role is admin, grants permission to edit the admin-default dashboard layout */
  canManageDashboardDefaults?: boolean;
  createdAt: string;
  digestCadence?: UserDigestCadence;
  /** IANA timezone, e.g. America/New_York */
  digestTimezone?: string;
  /** Has a confirmed MFA factor (#279). Only populated by GET /users; omitted elsewhere. */
  mfaEnabled?: boolean;
}
