/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

export type WidgetPlacementType = (typeof WidgetPlacementType)[keyof typeof WidgetPlacementType];

export const WidgetPlacementType = {
  service_status: 'service_status',
  recent_changes: 'recent_changes',
  alert_summary: 'alert_summary',
  sync_activity: 'sync_activity',
  docs_health: 'docs_health',
} as const;
