/**
 * Aggregated MSW handlers — every endpoint in docs/openapi.yaml, served from
 * orval-generated faker mocks. Each generated `get<Tag>Mock()` returns that tag's
 * handler array; we spread them all into one list.
 *
 * Regenerated by `npm run gen:api`; if you add a tag to the spec, add it here.
 */
import { curatedHandlers } from './curated';
import { getAlertsMock } from '../api/generated/alerts/alerts.msw';
import { getAuthMock } from '../api/generated/auth/auth.msw';
import { getChangesMock } from '../api/generated/changes/changes.msw';
import { getConnectorsMock } from '../api/generated/connectors/connectors.msw';
import { getDashboardMock } from '../api/generated/dashboard/dashboard.msw';
import { getDocsMock } from '../api/generated/docs/docs.msw';
import { getMeMock } from '../api/generated/me/me.msw';
import { getSettingsMock } from '../api/generated/settings/settings.msw';
import { getSystemMock } from '../api/generated/system/system.msw';
import { getTemplatesMock } from '../api/generated/templates/templates.msw';
import { getUsersMock } from '../api/generated/users/users.msw';

export const handlers = [
  // Curated fixtures first — MSW first-match wins, so these override the faker
  // mocks for the showcased surfaces. Everything else falls through below.
  ...curatedHandlers,
  ...getAuthMock(),
  ...getMeMock(),
  ...getUsersMock(),
  ...getDashboardMock(),
  ...getConnectorsMock(),
  ...getDocsMock(),
  ...getTemplatesMock(),
  ...getChangesMock(),
  ...getAlertsMock(),
  ...getSettingsMock(),
  ...getSystemMock(),
];
